version: "3"

networks:
  app-network:
    driver: bridge


    
services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    expose:
      - "3306"
    ports:
      - "3306:3306"          
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: inetum

    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
  
  back:
      container_name: back
      build: .
      expose:
        - "3000"
      ports:
        - "3000:3000"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inetum  
      depends_on:
        - postgres
      networks:
        - app-network  
      restart: unless-stopped   
   
  nginx:
      container_name: front
      image: nginx
      expose:
        - "80"
      ports:
        - "80:80"
      volumes:
        - ./dist:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/nginx.conf
      networks:
        - app-network  
      restart: unless-stopped
volumes:
  pgdata:
    driver: local
    
  pgconf:
    driver: local
  pglog: 
    driver: local
